apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: complexmeshes.complexmesh.kiali.io
  namespace: kiali-test-mesh-operator
spec:
  group: complexmesh.kiali.io
  names:
    kind: ComplexMesh
    listKind: ComplexMeshList
    plural: complexmeshes
    singular: complexmesh
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true