apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiali-test-mesh-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kiali-test-mesh-operator
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        name: kiali-test-mesh-operator
    spec:
      serviceAccountName: kiali-test-mesh-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          image: {{ kiali.test_mesh.operator.image }}
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
          env:
            - name: ANSIBLE_VERBOSITY
              value: "2"
        - name: operator
          image: {{ kiali.test_mesh.operator.image }}
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kiali-test-mesh-operator"
      volumes:
        - name: runner
          emptyDir: {}
