apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: redhattutorials.redhattutorial.kiali.io
spec:
  group: redhattutorial.kiali.io
  names:
    kind: RedHatTutorial
    listKind: RedHatTutorialList
    plural: redhattutorials
    singular: redhattutorial
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
