kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kiali-test-mesh-operator
  namespace: "{{ kiali.test_mesh.operator.namespace }}"
subjects:
- kind: ServiceAccount
  name: kiali-test-mesh-operator
  namespace: "{{ kiali.test_mesh.operator.namespace }}"
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
