- name: Get roles
  k8s_facts:
   api_version: rbac.authorization.k8s.io/v1
   kind: Role
   namespace: "{{ item[0] }}"
   name: "{{ item[1] }}"
  register: roles
  with_nested:
  - "{{ kiali.accessible_namespaces }}"
  - ['kiali', 'kiali-viewer']

- name: Assert that namespaces have the correct roles
  assert:
    that: "{{ item.resources | length == 1 }}"
  with_items:
  - "{{ roles.results }}"

- name: Get role binding
  k8s_facts:
   api_version: rbac.authorization.k8s.io/v1
   kind: RoleBinding
   namespace: "{{ item[0] }}"
   name: "{{ item[1] }}"
  register: rolebindings
  with_nested:
  - "{{ kiali.accessible_namespaces }}"
  - kiali

- name: Assert the role binding provides the read-only viewer role
  assert:
    that:
    - "{{ item.resources[0] | default({}) | json_query('roleRef.name') == 'kiali-viewer' }}"
    fail_msg: "The kiali role binding did not have the read-only roleref 'kiali-viewer'"
  with_items:
  - "{{ rolebindings.results }}"
